# This is a basic workflow to help you get started with Actions

name: Node Continuous Integration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
      - run: npm run build
  sonarQubeTrigger:
      name: SonarQube Trigger
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v3
      - name: Run sonarqube
        run: sonar-scanner
             -Dsonar.organization=1corp 
             -Dsonar.projectKey=sonar-test
             -Dsonar.sources=$GITHUB_WORKSPACE 
             -Dsonar.host.url="https://youthful-gates-6c0728.netlify.app/",
             -Dsonar.login=${{ secrets.SONAR_TOKEN }}
             -Dsonar.exclusions="**/*.test.tsx",
             -Dsonar.tests="./src",
             -Dsonar.test.inclusions="**/*.test.tsx,**/*.test.ts",
             -Dsonar.typescript.lcov.reportPaths="coverage/lcov.info",
             -Dsonar.testExecutionReportPaths="test-report.xml",
             -Dsonar.eslint.reportPaths="eslint-report.json",
